### ISSUE TITLE
Query regarding Opensource Clustering

### ISSUE THREAD

**Issue by abhilash07** [dalmatinerdb/dalmatinerdb#100]
Dear Sir/Madam thanks for your Open-Source its really awesome, you  people are doing good job keep it up. Recently our company is developing monitoring solution we found Dalmatiner Time Series Database is best for our project. But we have small query regarding clustering, is your respective Dalmatiner Open-Source Database supports clustering technology. If supports up-to which version it supports or it will supports upto latest release version. Thanks in advance.

Best Regards
Abhilash S

**Comment by Licenser** [comment]
Hi Abhilash,
all versions of DalmatinerDB use clustering and as it's one of it's core principles. I don't ever see that ever to change, and even if I wanted to it'd be a unreasonable amount of work ;).

Cheers,
Heinz

**Comment by abhilash07** [comment]
Hi Heinz, Thanks for our email and quick response. Your information is
valuable to us.

I have another question is  DalmatinerDB supports int64, float64, bool and
string datatypes like influxdb ? Thanks in advance.

Regards

Abhilash S
