### ISSUE TITLE
Creating a new bucket via ddb-admin

### ISSUE THREAD

**Issue by mohsalsaleem** [dalmatinerdb/dalmatinerdb#103]
./ddb-admin member-status
================================= Membership ==================================
Status     Ring    Pending    Node
-------------------------------------------------------------------------------
valid     100.0%      --      'dalmatinerdb@127.0.0.1'
-------------------------------------------------------------------------------
Valid:1 / Leaving:0 / Exiting:0 / Joining:0 / Down:0

./ddb-admin buckets create test
RPC to 'dalmatinerdb@127.0.0.1' failed: {'EXIT',
                                         {function_clause,
                                          [{dalmatiner_console,create,
                                            [["test"]],
                                            [{file,
                                              "/home/ec2-user/softwares/dalmatinerdb/_build/prod/lib/dalmatiner_db/src/dalmatiner_console.erl"},
                                             {line,23}]},
                                           {rpc,'-handle_call_call/6-fun-0-',
                                            5,
                                            [{file,"rpc.erl"},{line,206}]}]}}
The location /home/ec2-user/softwares/dalmatinerdb is where I created the build and then copied the ddb under rel to /data/dalmatinerdb

**Comment by Licenser** [comment]
The syntax for `buckets create` is:

```
buckets create <bucket> <res> <ppf> [<TTL> [<Grace>]]     - creates a new bucket
```

where `res` is the resolution, `ppf` is points per file `ttl` is how long the data is kept and `grace` is the grace period for out of order log entires.

for example:
```
ddb-admin buckets create test 10s 1d 1w
```
