### ISSUE TITLE
Unable to fetch binaries of 0.2.0 release

### ISSUE THREAD

**Issue by discovergy** [dalmatinerdb/dalmatinerdb#105]
Hello,

According to this: https://gist.github.com/sacreman/9015bf466b4fa2a654486cd79b777e64
I can fetch compiled binaries with: wget http://deb.project-fifo.net/releases/latest/dalmatinerdb_0.2.0_amd64.deb

But it doesn't work! 

Compiling from sources in Ubuntu VM produces some erlang errors, so I'd rather have binary. 

Regards, Stepan.

**Comment by Licenser** [comment]
those packages don't exist any more, the gist is also not maintained by us, please use the original documentation.
