### ISSUE TITLE
Write FSM 

### ISSUE THREAD

**Issue by davecromberge** [dalmatinerdb/dalmatinerdb#11]
It appears as if the Write FSM module is not being used by DalmatinerDB, at least at my cursory inspection.  Confusingly, the metric API to the VNode is non-symmetrical for R/W in terms of co-ordinating responses, and can lead to confusion.  For example, when reading from Dalmatiner, the Metric module delegates the read to the read FSM, whose responsible it is to ensure a proper quorum read:
```erlang
get(Bucket, Metric, PPF, Time, Count) when
      Time div PPF =:= (Time + Count - 1) div PPF->
    folsom_metrics:histogram_timed_update(
      get, dalmatiner_read_fsm, start,
      [{metric_vnode, metric}, get, {Bucket, {Metric, Time div PPF}},
       {Time, Count}]).
```

For writes, I do not see a similar delegating call to the write FSM:

```erlang
put(Bucket, Metric, Time, Value) ->
    {ok, N} = application:get_env(dalmatiner_db, n),
    {ok, W} = application:get_env(dalmatiner_db, w),
    PPF = dalmatiner_opt:ppf(Bucket),
    folsom_metrics:histogram_timed_update(
      put,
      fun() ->
              put(Bucket, Metric, PPF, Time, Value, N, W)
      end).
```
Confusingly, the quorum consistency check on W occurs in [metric.erl](https://github.com/dalmatinerdb/dalmatinerdb/blob/dev/apps/dalmatiner_db/src/metric.erl#L79) itself:
```
do_wait(0, _ReqID) ->
    ok;

do_wait(W, ReqID) ->
    receive
        {ReqID, ok} ->
            do_wait(W - 1, ReqID)
    after
        5000 ->
            {error, timeout}
    end.
```

@Licenser, I would like to know what I am missing, or if there is a special reason for the "exclusion" of the write FSM at this point?  I can submit a PR correcting this or add to the documentation if that will help, but I would like to make sure that I am not missing something first. 
Thanks.

**Comment by Licenser** [comment]
A long explanation was in the talk I gave on the EFL (video is up now), so I'll just give a short summary.

There are a lot more writes then reads, with tens of thousands of metrics having a own FSM either spawned or taken from a pool has a serious impact on performance, so doing it in the tcp handler connection itself improves performance by a lot.

**Comment by davecromberge** [comment]
@Licenser thanks for the quick response, I will take a look at the video.  Your short explanation does make sense, considering a load profile that is write heavy.  Thanks, will close the issue.
