### ISSUE TITLE
How to insert/import data? (better documents need)

### ISSUE THREAD

**Issue by jacktang** [dalmatinerdb/dalmatinerdb#111]
Hello,

I fllow the link https://blog.dataloop.io/top10-open-source-time-series-databases and know dalmatinerdb. I download the source code and compile it using rebar3 and make the erlang application run. And I try to run some queries according the doc (https://dalmatiner.readme.io/docs). The first question for me is how to import data into ddb? I need to write some code via ddb-client? and how about the queries? no command line client available right now?

BR
-Jack

**Comment by Licenser** [comment]
please look at this document: https://dalmatiner.readme.io/docs/dp-configuration

**Comment by Licenser** [comment]
assuming this is answered.
