### ISSUE TITLE
Server crash on start on Ubuntu 14.04

### ISSUE THREAD

**Issue by teamurko** [dalmatinerdb/dalmatinerdb#112]
I built ddb from source v0.3.0, with erlang=1:18.2 on Ubuntu 14.04, roughly following instructions on https://dalmatiner.readme.io/docs.

`ddb start` completed
root@ddb1:/data/dalmatinerdb/log# ps aux | grep dalmatiner
dalmati+ 119388  0.0  0.0   7492   316 ?        S    21:58   0:00 /data/dalmatinerdb/erts-7.2/bin/epmd -daemon
dalmati+ 120333  0.0  0.0  14856   788 ?        S    22:10   0:00 /data/dalmatinerdb/erts-7.2/bin/run_erl -daemon /tmp/dalmatiner/ /data/dalmatinerdb/log exec /data/dalmatinerdb/bin/ddb console
dalmati+ 120334 51.5  0.7 6704120 230408 pts/0  Ssl+ 22:10   5:35 /data/dalmatinerdb/erts-7.2/bin/beam.smp -P 256000 -e 256000 -Q 65536 -A 64 -K true -W w -- -root /data/dalmatinerdb -progname ddb -- -home /home/dalmatiner -- -boot /data/dalmatinerdb/releases/0.3.1/ddb -embedded -config /data/dalmatinerdb/db/generated.configs/app.2017.02.15.22.10.05.config -setcookie erlang -name ddb1@127.0.0.1 -smp enable -vm_args /data/dalmatinerdb/db/generated.configs/vm.2017.02.15.22.10.05.args -- console
dalmati+ 120504  0.0  0.0   4324   604 ?        Ss   22:10   0:00 /data/dalmatinerdb/lib/os_mon-2.4/priv/bin/memsup
dalmati+ 120505  0.0  0.0   4324   356 ?        Ss   22:10   0:00 /data/dalmatinerdb/lib/os_mon-2.4/priv/bin/cpu_sup

`tail -f log/*.log` shows a lot of errors, please look at log entry from crash.log below

2017-02-15 22:12:58 =CRASH REPORT====
  crasher:
    initial call: poolboy:init/1
    pid: <0.14492.5>
    registered_name: []
    exception exit: {{undef,[{k6_bytea,new,[960],[]},{metric_vnode,do_put,5,[{file,"/root/dalmatinerdb/_build/prod/lib/metric_vnode/src/metric_vn
ode.erl"},{line,510}]},{lists,foldl,3,[{file,"lists.erl"},{line,1262}]},{metric_vnode,handle_command,3,[{file,"/root/dalmatinerdb/_build/prod/lib
/metric_vnode/src/metric_vnode.erl"},{line,228}]},{riak_core_vnode,vnode_command,3,[{file,"/root/dalmatinerdb/_build/default/lib/riak_core/src/ri
ak_core_vnode.erl"},{line,374}]},{gen_fsm,handle_msg,7,[{file,"gen_fsm.erl"},{line,518}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{lin
e,240}]}]},[{gen_fsm,terminate,7,[{file,"gen_fsm.erl"},{line,626}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}
    ancestors: [<0.14491.5>,<0.14481.5>,riak_core_vnode_sup,riak_core_sup,<0.154.0>]
    messages: []
    links: [<0.14495.5>,<0.14497.5>,<0.14498.5>,<0.14496.5>,<0.14493.5>,<0.14494.5>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 1598
    stack_size: 27
    reductions: 470
  neighbours:
    neighbour: [{pid,<0.14494.5>},{registered_name,[]},{initial_call,{riak_core_vnode_worker,init,['Argument__1']}},{current_function,{gen_server
,loop,6}},{ancestors,[<0.14493.5>,<0.14492.5>,<0.14491.5>,<0.14481.5>,riak_core_vnode_sup,riak_core_sup,<0.154.0>]},{messages,[]},{links,[<0.1449
3.5>,<0.14492.5>]},{dictionary,[]},{trap_exit,false},{status,waiting},{heap_size,233},{stack_size,9},{reductions,20}]
    neighbour: [{pid,<0.14496.5>},{registered_name,[]},{initial_call,{riak_core_vnode_worker,init,['Argument__1']}},{current_function,{gen_server
,loop,6}},{ancestors,[<0.14493.5>,<0.14492.5>,<0.14491.5>,<0.14481.5>,riak_core_vnode_sup,riak_core_sup,<0.154.0>]},{messages,[]},{links,[<0.1449
3.5>,<0.14492.5>]},{dictionary,[]},{trap_exit,false},{status,waiting},{heap_size,233},{stack_size,9},{reductions,20}]
    neighbour: [{pid,<0.14498.5>},{registered_name,[]},{initial_call,{riak_core_vnode_worker,init,['Argument__1']}},{current_function,{gen_server
,loop,6}},{ancestors,[<0.14493.5>,<0.14492.5>,<0.14491.5>,<0.14481.5>,riak_core_vnode_sup,riak_core_sup,<0.154.0>]},{messages,[]},{links,[<0.1449
3.5>,<0.14492.5>]},{dictionary,[]},{trap_exit,false},{status,waiting},{heap_size,233},{stack_size,9},{reductions,20}]
    neighbour: [{pid,<0.14497.5>},{registered_name,[]},{initial_call,{riak_core_vnode_worker,init,['Argument__1']}},{current_function,{gen_server
,loop,6}},{ancestors,[<0.14493.5>,<0.14492.5>,<0.14491.5>,<0.14481.5>,riak_core_vnode_sup,riak_core_sup,<0.154.0>]},{messages,[]},{links,[<0.1449
3.5>,<0.14492.5>]},{dictionary,[]},{trap_exit,false},{status,waiting},{heap_size,233},{stack_size,9},{reductions,20}]
    neighbour: [{pid,<0.14495.5>},{registered_name,[]},{initial_call,{riak_core_vnode_worker,init,['Argument__1']}},{current_function,{gen_server
,loop,6}},{ancestors,[<0.14493.5>,<0.14492.5>,<0.14491.5>,<0.14481.5>,riak_core_vnode_sup,riak_core_sup,<0.154.0>]},{messages,[]},{links,[<0.1449
3.5>,<0.14492.5>]},{dictionary,[]},{trap_exit,false},{status,waiting},{heap_size,233},{stack_size,9},{reductions,20}]
2017-02-15 22:12:58 =ERROR REPORT====
** Generic server <0.14396.5> terminating
** Last message in was {'EXIT',<0.14395.5>,{undef,[{k6_bytea,new,[960],[]},{metric_vnode,do_put,5,[{file,"/root/dalmatinerdb/_build/prod/lib/metr
ic_vnode/src/metric_vnode.erl"},{line,510}]},{lists,foldl,3,[{file,"lists.erl"},{line,1262}]},{metric_vnode,handle_command,3,[{file,"/root/dalmat
inerdb/_build/prod/lib/metric_vnode/src/metric_vnode.erl"},{line,228}]},{riak_core_vnode,vnode_command,3,[{file,"/root/dalmatinerdb/_build/defaul
t/lib/riak_core/src/riak_core_vnode.erl"},{line,374}]},{gen_fsm,handle_msg,7,[{file,"gen_fsm.erl"},{line,518}]},{proc_lib,init_p_do_apply,3,[{fil
e,"proc_lib.erl"},{line,240}]}]}}
** When Server state == {state,{<0.14396.5>,poolboy_sup},simple_one_for_one,[{child,undefined,riak_core_vnode_worker,{riak_core_vnode_worker,star
t_link,[[{worker_module,riak_core_vnode_worker},{worker_args,[45671926166590716193865151022383844364247891968,[],worker_props,<0.14394.5>]},{work
er_callback_mod,metric_worker},{size,5},{max_overflow,0}]]},temporary,5000,worker,[riak_core_vnode_worker]}],{set,5,16,16,8,80,48,{[],[],[],[],[]
,[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[],[<0.14397.5>],[<0.14398.5>],[<0.14399.5>],[<0.14400.5>],[<0.14401.5>],[],[],[],[],[],[]}}},0,
1,[],poolboy_sup,{riak_core_vnode_worker,[{worker_module,riak_core_vnode_worker},{worker_args,[45671926166590716193865151022383844364247891968,[]
,worker_props,<0.14394.5>]},{worker_callback_mod,metric_worker},{size,5},{max_overflow,0}]}}
** Reason for termination ==
** {'module could not be loaded',[{k6_bytea,new,[960],[]},{metric_vnode,do_put,5,[{file,"/root/dalmatinerdb/_build/prod/lib/metric_vnode/src/metr
ic_vnode.erl"},{line,510}]},{lists,foldl,3,[{file,"lists.erl"},{line,1262}]},{metric_vnode,handle_command,3,[{file,"/root/dalmatinerdb/_build/pro
d/lib/metric_vnode/src/metric_vnode.erl"},{line,228}]},{riak_core_vnode,vnode_command,3,[{file,"/root/dalmatinerdb/_build/default/lib/riak_core/s
rc/riak_core_vnode.erl"},{line,374}]},{gen_fsm,handle_msg,7,[{file,"gen_fsm.erl"},{line,518}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"}
,{line,240}]}]}

Looks like some modules are missing. Do you have ideas why it might be happening?

**Comment by Licenser** [comment]
Hi Mate,
k6_bytea is a c-module that is used to provide some performance advantages. Could it be that it compiled with an error /failed? Alternatively did you compile on the same host or moved it?

**Comment by teamurko** [comment]
Hey. Thanks for you quick response. Thanks for advice of checking compilation output. I didn't find anything suspicious. But I noticed that I messed up versions because I tried to test dev vs 0.3.0 vs 0.2.0 without proper cleanup. So, just removing _build folder and rebuilding 0.3.0 from scratch helped. No crash reports so far.

**Comment by Licenser** [comment]
Wonderful :) glad to hear that worked!

Cheers,
Heinz
