### ISSUE TITLE
Proper way to query from an Erlang app

### ISSUE THREAD

**Issue by benjamin-bergia** [dalmatinerdb/dalmatinerdb#117]
What is the recommended way to query DalmatinerDB from an Erlang application ?
I might be wrong there but, contrary to the [JS client library](https://github.com/dalmatinerdb/ddb-query-js/tree/master/src), the [Erlang one](https://github.com/dalmatinerdb/ddb_client) doesn't seem to support DQL.

Should my application include both the client library and the query engine in order to get all DQL goodness ?

**Comment by Licenser** [comment]
Hi,
you can embed the [query engine](https://github.com/dalmatinerdb/dqe) directly into an erlang application. This safe the cost for http, encoding and decoding compared to outside libraries :).

it then becomes as simple (I should be careful with that word) as `dqe:run("<your awesome query>").`

**Comment by benjamin-bergia** [comment]
@Licenser Thanks. I will give it a try.

**Comment by Licenser** [comment]
assuming this is answered

**Comment by benjamin-bergia** [comment]
Yep thanks.
