### ISSUE TITLE
Fail buld from source

### ISSUE THREAD

**Issue by zaabjuda** [dalmatinerdb/dalmatinerdb#119]
`$ pwd
/Users/dmitriy.zhiltsov/dalmatinerdb

$ DEBUG=1 make rel`
And i see

`===> Provider successfully run: resolve_release
===> Running provider release
===> Provider (release) failed with: {error,eacces}
===> Uncaught error in rebar_core. Run with DEBUG=1 to see stacktrace or consult rebar3.crashdump
===> Uncaught error: function_clause
===> Stack trace to the error location:
[{relx,format_error,
       [{error,eacces}],
       [{file,"/home/tristan/Devel/rebar3/_build/default/lib/relx/src/relx.erl"},
        {line,220}]},
 {relx,report_error,2,
       [{file,"/home/tristan/Devel/rebar3/_build/default/lib/relx/src/relx.erl"},
        {line,336}]},
 {rebar_relx,do,4,
             [{file,"/home/tristan/Devel/rebar3/_build/default/lib/rebar/src/rebar_relx.erl"},
              {line,38}]},
 {rebar3_cuttlefish_release,do,1,
                            [{file,"/Users/dmitriy.zhiltsov/dalmatinerdb/_build/default/plugins/rebar3_cuttlefish/src/rebar3_cuttlefish_release.erl"},
                             {line,89}]},
 {rebar_core,do,2,
             [{file,"/home/tristan/Devel/rebar3/_build/default/lib/rebar/src/rebar_core.erl"},
              {line,153}]},
 {rebar_prv_do,do_tasks,2,
               [{file,"/home/tristan/Devel/rebar3/_build/default/lib/rebar/src/rebar_prv_do.erl"},
                {line,57}]},
 {rebar_core,do,2,
             [{file,"/home/tristan/Devel/rebar3/_build/default/lib/rebar/src/rebar_core.erl"},
              {line,153}]},
 {rebar3,main,1,
         [{file,"/home/tristan/Devel/rebar3/_build/default/lib/rebar/src/rebar3.erl"},
          {line,66}]}]
===> When submitting a bug report, please include the output of `rebar3 report "your command"`
make: *** [rel] Error 1`

I think the paths is similar to /home/tristan/ is hardcoded in rebar3 binary

**Comment by Licenser** [comment]
Hi this sadly a known problem with rebar3 at the moment: https://github.com/erlang/rebar3/issues/1441 it's espeically related to OS X it seems.

I hate myself for suggesting it but there is docker compose setup for testing things out: https://github.com/dalmatinerdb/docker-ddb-compose

**Comment by Licenser** [comment]
There is a workaround:
```
chmod -R u+w /usr/local/Cellar/erlang/*/lib/erlang/lib/*/ebin/*.app
```

**Comment by zaabjuda** [comment]
Thx!
