### ISSUE TITLE
[Question] What need to be included in backup

### ISSUE THREAD

**Issue by it-praktyk** [dalmatinerdb/dalmatinerdb#120]
Hi!

What does need to be included in backup (what will be stored on tape) to successfully restore DalmatinerDB ?

I assume that
- /data/dalmatinerfe/etc/* - the path based on the Project FiFo [Installation instruction](https://docs.project-fifo.net/docs/ddb-installation-old)
- PostgreSQL database
- files from ZFS volumes

Is it OK?

**Comment by Licenser** [comment]
The PostresSQL database for once, and I'd just take the entire `/data/dalmatinerdb` folder. You could go with `/data/dalmatinerfe` as well but this is only configuration data FE has no state on it's own.

A bit background: All of the Project-FiFo components follow the logic that all 'mutable' data lives in `/data/<component>` That way backing things up is rather simple by just taking that all.

**Comment by it-praktyk** [comment]
Thank you for explanation.
