### ISSUE TITLE
Compiling on ubuntu

### ISSUE THREAD

**Issue by saichandra286** [dalmatinerdb/dalmatinerdb#135]
i tried to compile source code using "./rebar3 as prod release", and getting this error.
Even in root mode still its getting same error 
===> Compiling getopt
===> Compiling cuttlefish
===> Building escript...
===> Compiling clique
===> Compiling chash
===> Compiling blume
===> Compiling basho_stats
===> Compiling riak_core
===> Compiling recon
===> Compiling ranch
===> Compiling ibrowse
===> Compiling dynamic_compile
===> Compiling otters
===> Compiling mcache
===> Compiling jsxd
===> Compiling hdr_histogram
===> Compiling /home/ubuntu/dalmatinerdb/_build/default/lib/hdr_histogram/c_src/hdr_histogram_nif.c
===> Compiling /home/ubuntu/dalmatinerdb/_build/default/lib/hdr_histogram/c_src/hdr_histogram.c
===> /home/ubuntu/dalmatinerdb/_build/default/lib/hdr_histogram/c_src/hdr_histogram.c:14:18: fatal error: zlib.h: No such file or directory
compilation terminated.

**Comment by Licenser** [comment]
the error tells you that you're missing the zlib headers, you'll need top install the package providing it. probably `libz` `zlib` or something like that.

**Comment by saichandra286** [comment]
cp etc/dalmatinerdb.conf.example /data/dalmatinerdb/etc/dalmatinerdb.conf
should we need to create these files manually(/data/dalmatinerdb/*)?

**Comment by Licenser** [comment]
/data/dalmatinerdb needs to be created it's where all mutable files go

**Comment by saichandra286** [comment]
".bin/ddb start" return empty output
how can i login into dalmatinerDb and run my querys

**Comment by Licenser** [comment]
It seems you're using the development branch not stable/release (master). Dev apparently had a problem, that should be fixed now.

Regarding how to query, read the documentation or use the docker image to test it out.
