### ISSUE TITLE
What if multiple systems post to same bucket metric?

### ISSUE THREAD

**Issue by neeraj9** [dalmatinerdb/dalmatinerdb#136]
What is the default behavior when multiple clients push a value for the same bucket metric? Are those values added together or last one wins?

I was toying with the idea of automatically discovering cluster nodes via this option but it doesnt seem to work. Do let me know if there is a setting to implement such a functionality.

**Comment by Licenser** [comment]
if multiple systems write to the same data point (aka same bucket + same metric + same dimensions) that's a usage error and leads to undefined behavior, namely some write wins.

**Comment by neeraj9** [comment]
The primary reason for this hack attempt was to work around the shortcomings in the ddb grafana plugin to get summation of some series.

Ddb-fe is good but having grafana like tool with complete support would have been great.

**Comment by Licenser** [comment]
I'm not sure what you're missing in the grafana plugin, you can use 'combine' functions to sum serieses?

Otherwise contributions to improve it are welcome: https://github.com/dalmatinerdb/dalmatinerdb-datasource

**Comment by neeraj9** [comment]
It is not clear how multiple series can be combined in the builder interface. Would be great if a pic is attached along with the basic doc.

**Comment by Licenser** [comment]
I don't think I understand what you are tying to do

**Comment by neeraj9** [comment]
Say I want to combine (sum) CPU across all my cluster machines, which are posting metric as 'node name'.'cpu' in the same bucket.
I do not know how multiple such nodes metric be combined in grafana query builder interface.

**Comment by Licenser** [comment]
You can't as the metric design is faled and prohebits sensible aggregation.

If however your metrics were `'system'.'cpu'` with the dimensions `node=<some node>` and `cluster=<some cluster>` you'd go by at as follows:

![image](https://user-images.githubusercontent.com/119093/28701848-52c0b482-7359-11e7-99ae-8af5084ba88b.png)

**Comment by neeraj9** [comment]
Great! I will correct my metric usage which is changing the metric prefix rather than using dimensions.
Thanks. 👍
Having said that it will be great to still combine independent metrics but that would be something for later.

**Comment by Licenser** [comment]
awesome!
basic rule of thumb:
* metric should be what never varies (i.e. system.cpu would never change for all possible srouces of this value)
* dimensiosn should be what identify the specific instance of a value (i.e. hostname, clusters if you want to aggregate over it and so on, could be cpu type if you need that info)

**Comment by neeraj9** [comment]
@Licenser Thanks!!

I have been building for some time now completely in Erlang/OTP and instead of existing monitoring solutions, DDB stood out as a great alternative. I am introducing ddb within my organization and would be happy to talk out loud once the system goes into production.

**Comment by Licenser** [comment]
Thanks mate  much appriciated :)
