### ISSUE TITLE
Backup at runtime

### ISSUE THREAD

**Issue by Odyldzhon** [dalmatinerdb/dalmatinerdb#140]
Hi!
Could you please, add to the documentation information about back up procedure.
I have found issue https://github.com/dalmatinerdb/dalmatinerdb/issues/120 with information what should be included in backup. 

The question is, can I make backup of `/data/dalmatinerdb` folder at runtime i.e. without restarting Dalmatinerdb?

**Comment by Licenser** [comment]
See: https://gitlab.com/Project-FiFo/DalmatinerDB/dalmatinerdb/issues/140
