### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by sungjun001** [dalmatinerdb/dalmatinerdb#143]
I get source from git. and follow commend.but It was Fail.
----------------------------------
~/dalmatinerdb$ ./rebar3 as prod release
===> No entry for profile prod in config.
===> Verifying dependencies...
===> Compiling riak_core
===> Compiling _build/default/lib/riak_core/src/riak_core_vnode_worker_pool.erl failed
_build/default/lib/riak_core/src/riak_core_vnode_worker_pool.erl:61: referring to built-in type queue as a remote type; please take out the module name
----------------------------------

**Comment by Licenser** [comment]
see: https://gitlab.com/Project-FiFo/DalmatinerDB/dalmatinerdb/issues/141
