### ISSUE TITLE
divide(<metric>, <metric>)

### ISSUE THREAD

**Issue by Licenser** [dalmatinerdb/dalmatinerdb#30]
divides two metrics

**Comment by danhanly** [comment]
This aggregate would be so useful for me. 

**Here's my usage scenario**
I'd like to track my logins, and I want to display a single stat which is effectively this:
`divide(total.login.requests, successful.login.requests)`
This would give me a perfect representation of the state of my login system. I'd be able to then multiply and create a percentage out of it.

**Comment by szarsti** [comment]
This sounds like a situation similar to #44. We could implement it just by adding _invert(<metric>*)_ function and use it together with _mul(<metric>*)_ combining function. In that case described scenario would become: `mul(total.login.requests, invert(successful.login.requests))`.
