### ISSUE TITLE
abs(<metric>)

### ISSUE THREAD

**Issue by Licenser** [dalmatinerdb/dalmatinerdb#33]
make metric positive

**Comment by sacreman** [comment]
Perhaps a more flexible function than https://github.com/dalmatinerdb/dalmatinerdb/issues/31 depending on how easy it would be to nest a derivative inside.

**Comment by Licenser** [comment]
nesting is no problem but it's a bit of a differnce, with abs(derivate(,,,)) you would still get a spike just in the posotive directio

**Comment by sacreman** [comment]
Ah yes, so the non_negative_derivative is probably more useful i'd forgotten about the change over time part :)

This is perhaps less so. I can't think of a reason why we would convert all numbers in a series to positive in a real world example. Although having said that Bosun (quite an advanced alerting platform) has the option. Might be worth making this low priority some how.

I've linked to a few places in various messages as I've been reading OpenTSDB, InfluxDB, Prometheus and SignalFX docs (couldn't find the Wavefront functions). There is a vast discrepancy between function names between all of these places in terms of what they do.

Bosun adds a few more fun ones:

https://bosun.org/expressions#reduction-functions
