### ISSUE TITLE
TOP / BOTTOM

### ISSUE THREAD

**Issue by Licenser** [dalmatinerdb/dalmatinerdb#35]

**Comment by sacreman** [comment]
We currently support a Top 10 dashboard widget which in future could be configured to give the top X results across one or many series. It's computed in the client which makes the laptop fan come on sometimes :)

<img width="360" alt="screen shot 2016-04-29 at 22 58 41" src="https://cloud.githubusercontent.com/assets/1873879/14930725/0f9b5786-0e5e-11e6-8f38-f42c8a3d346f.png">

**Comment by Licenser** [comment]
The big question is what is top, lets example this out (lets call it sort for the sake of ti)

|time | t0 | t1 | t2 | t3 | t4 | t5 |
|-------|----|----|----|----|----|----|
| s.0 | 10 | 7 | 8 | 13 | 5 | 3 |
| s.1 | 9 | 11 | 8 | 5 | 12 | 15 |
| s.1 | 19 | 3 | 5 | 23 | 2 | 0 |

Lets take those as an example, how would the query look like?

`SELECT sort(s.* BUCKET 'whatever') LAST 6`

What would shoud return? And why?

**Comment by sacreman** [comment]
With our current Top X widget the current value would be latest value and the widget would dynamically move the series up and down.

So it would start with S.2 on top, lots of wobbling would happen, and it would end with s.1 on top.

However, there is another use case to consider, which we don't currently do. The example is from Prometheus where they want to get Top 3 CPU users grouped by application (app) and process type (proctype).

`topk(3, sum(rate(instance_cpu_time_ns[5m])) by (app, proc))`

I believe that returns the top at a particular time. They have had requests for more complicated versions that return an average or area under the series to determine the overall top for the range. I've not played with that much so I don't know how valuable it is. An interesting thread is here:

https://github.com/prometheus/prometheus/issues/586

**Comment by or4cle** [comment]
We have found this function particularly useful in dashboards:

http://graphite.readthedocs.io/en/latest/functions.html#graphite.render.functions.highestMax 

I am not sure prometheus has an equivalent, but it would definitely be beneficial!

**Comment by Licenser** [comment]
current state of lanning:

```sql
SELECT s.* BUCKET bla LIMIT 3 WITH max() ORDER asc Last 6
```

**Comment by Licenser** [comment]
TOP and BOTTOM are now part of the query engine.
