### ISSUE TITLE
stddev(<histogram>)

### ISSUE THREAD

**Issue by Licenser** [dalmatinerdb/dalmatinerdb#37]
Calculates the std deviation for a histogram

**Comment by sacreman** [comment]
At some point in the UI we'll probably want to draw 1, 2 and 3 sigma standard deviation lines on threshold graphs. Then make it easy and quick for people to choose how close a fit they would like.

**Comment by Licenser** [comment]
Lets, just as an exercise, pretend I don't know what the something something sigma is, how would we explain that to someone that doens't know that? :P

**Comment by sacreman** [comment]
I think you draw a line through the graph at the mean. Then draw another line across the max and the min. Then you create another line above (and below) the min and max line and make it the same distance as the first line again from the mean. Then do the same again and again.

They typically do it on alerting systems. It's a bit rubbish for actually alerting properly, but it does cut down on some noise. There is a mathematical definition of the sigma stuff involving squares of the mean etc, but I just remember the simple line drawing stuff :)

**Comment by Licenser** [comment]
merged @davecromberge function for doing this on metrics as well as have it for histograms.
