### ISSUE TITLE
first(?)

### ISSUE THREAD

**Issue by Licenser** [dalmatinerdb/dalmatinerdb#39]

**Comment by Licenser** [comment]
Does this make sense? Why not use a query that just queries the first wanted element? Where is the difference?

**Comment by sacreman** [comment]
The motivation for this came from our single number widget which can be configured to display just a single value (last seen value when on a single series).

@szarsti has implemented something for this here: https://github.com/dataloop/dalmatiner-frontend/commit/ea681d72359436ea83ba9ce9301caf98d3a56968

There was some discussion around using the empty() function to achieve the same result.

**Comment by sacreman** [comment]
We can close this one too
