### ISSUE TITLE
timeshift(<metric>, <time>)

### ISSUE THREAD

**Issue by Licenser** [dalmatinerdb/dalmatinerdb#43]
Moves the time for a sub-query

**Comment by sacreman** [comment]
We plan to add a realtime metrics browser into Dataloop in the next few months. This will be our playpen for analytics and a different use case than dashboard widgets. In this new area it will be a single large chart with cool query functions below. Being able to overlay a shadow of yesterdays data, in real time, alongside data happening right now to see difference would be awesome. SignalFX does this.

https://support.signalfx.com/hc/en-us/articles/203761489-SignalFlow-analytics-reference-guide#timeshift

**Comment by Licenser** [comment]
This is implemented using the `SHIFT BY` syntax.
