### ISSUE TITLE
sub(<metric>, <metric>)

### ISSUE THREAD

**Issue by Licenser** [dalmatinerdb/dalmatinerdb#44]
Isn't this either derivate/1 or sub/2 ?

**Comment by sacreman** [comment]
Yes, I think it probably is. I didn't see sub/2 in the docs - we can close. It was purely for working out for a particular window what the difference is between the first and last value.

**Comment by Licenser** [comment]
there isn't a sub ;) but it'd be an option

**Comment by szarsti** [comment]
We could also consider just adding _negate()_, so one can build substraction as _add(A, negate(B))_. An advantage of that approach would be more flexibility. One could then mix multiple add and subtract operations in single call, because _sum(<metric>*)_ accept any number of metrics.

**Comment by Licenser** [comment]
that's an interesting approach :) not sure if performance wise it's better, function calls are not super cheap.

At least UI (Query language wise) I think having a sub is more intuitive, weather we implement sub with negate(, or negate with sub?) or make a very own function we can change that behind the scene but writing `sub(A, B)` will feel easier to udnerstand then`add(A, negate(B))` from a QL perspective.
