### ISSUE TITLE
sort_asc(?)

### ISSUE THREAD

**Issue by Licenser** [dalmatinerdb/dalmatinerdb#45]

**Comment by sacreman** [comment]
Similar to https://github.com/dalmatinerdb/dalmatinerdb/issues/46 and could potentially be a single function if there was a syntax to sort asc or desc.

**Comment by Licenser** [comment]
I'm convinced sorting by names is a lot easier to do at the time the query is drawn, the required code for that is about 1 line, for adding logic of sorting into the query engine it's orders of magnitude more complicated. Also queries are sorted by the order they are written (same as for SQL) changing that sorting would seem wrong.
