### ISSUE TITLE
add bucket resolution command to the protocol

### ISSUE THREAD

**Issue by Licenser** [dalmatinerdb/dalmatinerdb#61]
get the reslution for a bucket

**Comment by davecromberge** [comment]
I think we should also include the ability to set the resolution for a bucket, as part of the protocol.  Perhaps an appropriate place is when opening a stream connection, however - there could be a scenario where the bucket already exists and the supplied desired resolution differs.  Currently, the resolution is read from riak metadata in the dalmatiner_opt module.   I would find this useful during data migration to create new buckets with the appropriate resolution.

**Comment by Licenser** [comment]
Doing that as part of the stream protocol is a very nice idea, however it would need to fail if a different resolution already existed, changing the resolution of a existing bucket is a no go as it would mean all the existing data gets invalid as the indexes differ. But that could simply fail and error out I guess.

**Comment by davecromberge** [comment]
I agree that resolution should remain fixed, almost part of its identity. 
Continuing this train of thought, from a metrics2.0 perspective on identity, does resolution form part of a metric identity?  It may be a good idea for us to specify the resolution as part of the system defined tags.

**Comment by davecromberge** [comment]
Actually, that may not make sense since the same metric may be stored in multiple buckets of varying resolution, with a summary function used to aggregate the values in a time period.

**Comment by Licenser** [comment]
I think metrics2.0 don't enforces anything to be part of the identity, but for Dalmatiner resolution definitely would make sense to have that.

Mixing resolutions in a summary function is quite hard, possible but not trivial you'll need to manually bring them to the same resolution before summarizing, think `sum('m@10s' bucket b, avg('m@1s' bucket b1, 10))` otherwise it's hard to define how to handle the summary and what the final resolution should be.
