### ISSUE TITLE
query ttl via tcp protocol

### ISSUE THREAD

**Issue by Licenser** [dalmatinerdb/dalmatinerdb#63]

**Comment by davecromberge** [comment]
This will be returned as part of the BUCKET_INFO query, along with PPF and Resolution.

**Comment by davecromberge** [comment]
@Licenser this issue can be closed.

**Comment by Licenser** [comment]
#72 Isnt' merged yet

**Comment by davecromberge** [comment]
This issue just applies to TTL though, which is bucket_info get as far as I understand.

**Comment by Licenser** [comment]
Oh I misread, sorry I thought this issue was to set it. you're totally right!
