### ISSUE TITLE
sum aggregates function

### ISSUE THREAD

**Issue by sacreman** [dalmatinerdb/dalmatinerdb#70]
I was trying to get a count of running containers. In dataloop I can use base.count across tag docker and select the sum widget which sums up the latest point across all series in a tag.

In Dalmatiner the sum() only seems to work on each series independently.

@szarsti suggested a sumover() function. I guess I'd also need a way to select last value too so it only summed up the last point.

**Comment by sacreman** [comment]
https://github.com/dalmatinerdb/dalmatinerdb-datasource/issues/4

**Comment by szarsti** [comment]
I think I have explained it badly. Dalmatiner allows for using sum to combine series. You just use it with one argument.

In grafana plugin though, function arguments count is something that is difficult to express, especially on function selector. I suggested using different function name for that.
