### ISSUE TITLE
how to get the host CPU usage

### ISSUE THREAD

**Issue by yang-wu** [dalmatinerdb/dalmatinerdb#74]
I want to get the host CPU usage,but only have the conf:
#cpu_stat:::user
#cpu_stat:::idle
#cpu_stat:::intr
#cpu_stat:::iowait
#cpu_stat:::syscall
#cpu_stat:::kernel

how to configure the CPU usage about host?

**Comment by Licenser** [comment]
Hi,
I don't really understand your question can you elaborate a bit?

**Comment by Licenser** [comment]
Do not open the same issue in multiple repositories this is deliberately wasting time.
