### ISSUE TITLE
Proposal: SELECT any FROM ... WHERE ...

### ISSUE THREAD

**Issue by szarsti** [dalmatinerdb/dalmatinerdb#75]
This is a proposal to add 'any' keyword as a selector. It will mean that selector would pick all metrics that have tag data matching WHERE clauses.

We can replace 'any' with 'all', or SQL like '*' if you think that would be reasonable.

I think we can easily implement with current indexer database schema.

Please note that it is slightly different to #71. This dose not involve metric path wild-card expansion.  It just allows for flexible metric selection driven by WHERE clause.

I think it can be very useful for many people that are getting metrics from various collectors where they have limited control how individual metrics are called. It would be also very useful mechanism to help people transit from path based selectors to meta-data based selectors. I imagine that when people start using meta-data they will decorate metrics first with extra data, without changing paths. In this intermediate stage being able to query by tags across many metrics would be very beneficial.

Also it could be a way to build a workaround for #71. In that case we could provide backward compatibility by mapping wild-card queries, for example:

```SELECT base.cpu.*.iowait FROM x```

, to someting like this:

```SELECT any FROM x WHERE ddb:name_1 = base AND ddb:name_2 = cpu AND ddb:name_4 = iowait```

If you accept this proposal, I am very happy to prepare pull-request implementing it.

**Comment by Licenser** [comment]
That does sound useful and yes it's totally different from wildcards. Reading further on arrays today https://github.com/dalmatinerdb/dqe_idx_pg/issues/11 even so I don't like it querying wildcards in metrics seems a lot more possible then I thought. I still think it's a potentially wrong approach but it'd be worth a try see how it performs?

Not sure what the best keyword would be `*` might be misleading as it would be more like `**` given it'd match all metrics not just some. `any` or `all` have the potential to collide with a metric, but escaping could solve that but would be harder read - we could use `ANY` / `ALL` that'd make it clearer it's a keyword but that's readability in the end. Another alternative, but I'm not liking it much would be using nothing as ing `SELECT FROM x WHERE ...`

**Comment by szarsti** [comment]
Cool,

I'll prepare some pull request with changes and we can have a further discussion about right keyword as a part of review.

**Comment by davecromberge** [comment]
@Licenser do you need anything further before we can mark this issue as closed?

**Comment by Licenser** [comment]
nope I just failed to keep track of it being closed :) To be sure `SELECT ALL FROM collection` is now valid syntax? I'll update the docs accordingly.

**Comment by davecromberge** [comment]
Yes it's valid syntax.

**Comment by Licenser** [comment]
cool then the docs are updated too :) great work!

**Comment by davecromberge** [comment]
Awesome, thanks - next time I will document as part of the task.
