### ISSUE TITLE
float64 or higher metric value precision

### ISSUE THREAD

**Issue by sacreman** [dalmatinerdb/dalmatinerdb#77]
DalmatinerDB currently supports 62 bits for values.

At lot of collection tools support float64 so there is an argument for increasing the precision.

This article looked very interesting:

http://ubiquity.acm.org/article.cfm?id=2913029

**Comment by szarsti** [comment]
I don't think that anyone will notice 1 bit of lost precision (we use literally double float without least significant bit). Do you have any real world use case that one bit would matter. Usually people loose that precision anyway when converting between decimal and binary floats.

I don't think there is any benefit of doing anything more than we do right now.

**Comment by Licenser** [comment]
👍 to @szarsti

**Comment by Licenser** [comment]
floats are always inprecise, 64 bit has to do with register size less with the need for precision. It's bit wanking that's all.

**Comment by sacreman** [comment]
It looks bad in the comparison table!

**Comment by Licenser** [comment]
lets make it simple: no ;)
