### ISSUE TITLE
Unable to run DalmatinerDB on Ubuntu 16.04

### ISSUE THREAD

**Issue by cdrx** [dalmatinerdb/dalmatinerdb#79]
Following the install instructions, installed `dalmatinerdb_0.2.0_amd64.deb` from deb.project-fifo.net.

Running `service ddb start` does not start DalmatinerDB. Looking in the logs, the service seems to crash:

```
Sep 13 15:50:33 server2 systemd[1]: Started DalmatinerDB.
Sep 13 15:50:34 server2 ddb[5166]: Node 'dalmatinerdb@127.0.0.1' not responding to pings.
Sep 13 15:50:36 server2 ddb[5166]: Exec: /usr/lib/ddb/erts-7.2/bin/erlexec -boot /usr/lib/ddb/releases/0.2.0/ddb -embedded  -config /var/lib/ddb/generated.configs/app.2016.09.13.15.50.35.config -args_file /var/lib/ddb/generated.configs/vm.2016.09.13.15.50.35.args -vm_args /var/lib/ddb/generated.configs/vm.2016.09.13.15.50.35.args  -- console -noinput +Bd
Sep 13 15:50:36 server2 ddb[5166]: Root: /usr/lib/ddb
Sep 13 15:50:36 server2 ddb[5166]: Starting up
Sep 13 15:50:37 server2 ddb[5166]: [os_mon] cpu supervisor port (cpu_sup): Erlang has closed
Sep 13 15:50:37 server2 systemd[1]: ddb.service: Main process exited, code=killed, status=4/ILL
Sep 13 15:50:37 server2 kernel: [  542.671619] traps: 2_scheduler[5295] trap invalid opcode ip:7f89a5030040 sp:7f89a827d0a0 error:0 in erocksdb.so[7f89a4f27000+249000]
Sep 13 15:50:37 server2 systemd[1]: ddb.service: Unit entered failed state.
Sep 13 15:50:37 server2 systemd[1]: ddb.service: Failed with result 'signal'.
```

This is running Ubuntu 16.04 64 bit on kernel 4.5.7

Any ideas how I can go about debugging this?

**Comment by davecromberge** [comment]
Hi @cdrx - I suspect this has to do with compiling rocks db in PORTABLE mode.
Unfortunately Debian builds are still manual at this stage and this could have slipped through.  Project FIFO are busy with a CI solution at the moment. Until that work is finished, I am happy to publish a new Debian package compiled under compatibility mode.  I will let you know when it is available if you are happy to download and install a new one.

**Comment by cdrx** [comment]
Sure, thanks.

**Comment by davecromberge** [comment]
I have uploaded a new Debian package, please could you give it a try and let us know if that fixes it.  Thanks for the feedback.

**Comment by cdrx** [comment]
Works perfectly, thanks so much for sorting so quickly! :)

**Comment by saichandra286** [comment]
does any one having  dalmatinerdb_0.2.0_amd64.deb please share a link

**Comment by Licenser** [comment]
Debian packages are not supported and 2.0 is quite outdated. Please compile it from the current source or if you just want to test use one of the docker images

**Comment by saichandra286** [comment]
@Licenser thanx for your valuable information, is der any proper docs to install DalmatinerDB on Ubuntu 16.04?

**Comment by Licenser** [comment]
Http://Docs.dalmatiner.io should cover it
