### ISSUE TITLE
Intallation using pkgin on smartos

### ISSUE THREAD

**Issue by rickardrosen** [dalmatinerdb/dalmatinerdb#82]
I'm new to smartos and pkgin and this is probably easily fixed, but documentation states:

>VERSION='dev' # use 'rel' for release packages
echo "http://release.project-fifo.net/pkg/${VERSION}/" >>/opt/local/etc/pkgin/repositories.conf
pkgin -fy up
pkgin install dalmatinerdb # To install the backend package

However, pkgin is unable to find the package using this repo configuration.

**Comment by rickardrosen** [comment]
Ok, so figured it out!

>echo "http://release.project-fifo.net/pkg/${VERSION}/" >>/opt/local/etc/pkgin/repositories.conf

should read:

>echo "http://release.project-fifo.net/pkg/${VERSION}" >>/opt/local/etc/pkgin/repositories.conf

Perhaps the documentation could be updated?

**Comment by Licenser** [comment]
Hi,
good catch! Thanks for reporting this. I think that behaviour changed recently. I've update the docs accordingly.
