### ISSUE TITLE
document (current version of) network protocol

### ISSUE THREAD

**Issue by tverbeke** [dalmatinerdb/dalmatinerdb#83]
https://dalmatiner.readme.io/docs/ddb-network-protocol

is empty for now. There is content at

http://dalmatinerdb.readthedocs.io/en/latest/proto.html

but I don't know whether it is current (the version number in any case says 0.1.0 compared to 0.2.0 on the readme.io site).

**Comment by Licenser** [comment]
the 0.1.0 is near identical but needs some small updates (and migratin)

**Comment by Licenser** [comment]
@szarsti will need your help on documenting the float encoding.
