### ISSUE TITLE
start dalmatinerdb community support channel

### ISSUE THREAD

**Issue by tverbeke** [dalmatinerdb/dalmatinerdb#84]
AFAICS the docs don't mention any channels for getting help or discussing about dalmatinerdb.

If we overlooked, maybe it is useful to add to the docs. If not, maybe it is worthwhile to start an IRC channel, Google groups mailing list, Gitter etc. (?)

**Comment by Licenser** [comment]
There is a #dalmatinerdb channel on Frenode, also the #Project-FiFo channel and the Project-FiFo mailing list.

Given DalmatinerDB is part of FiFo I don't think it needs to be separated and the existing community will be benificial.

I agree non the less that this needs a mention somewhere.

**Comment by Licenser** [comment]
All updated in the docs: https://dash.readme.io/project/dalmatiner/v0.2.0/docs/getting-in-contact
