### ISSUE TITLE
Understanding behavior of dalmatinerdb on benchmark

### ISSUE THREAD

**Issue by nginn** [dalmatinerdb/dalmatinerdb#98]
Hi everyone,
I've tried to run the benchmark from [here](https://gist.github.com/sacreman/b77eb561270e19ca973dd5055270fb28) on my less equipped server: 16GB RAM, 8 CPU with SSD disk. Benchmark results for my disk are:
```
READ: io=3071.7MB, aggrb=32217KB/s, minb=32217KB/s, maxb=32217KB/s, mint=97631msec, maxt=97631msec
  WRITE: io=1024.4MB, aggrb=10743KB/s, minb=10743KB/s, maxb=10743KB/s, mint=97631msec, maxt=97631msec
```
I understand that my server couldn't handle the same load described in the benchmark so I've tried to add haggar workers gradually and started with 2 of them. They've created around 800k MPS and first 5-6 hours everything worked quite well: LA on server was only around 20, and dalmatiner used only about 8GB of RAM and about 2 cpus.
So I left it to work for some time, and on the next day I've noticed that the same queries (like `SELECT 'dalmatinerdb@127.0.0.1'.'mps' BUCKET 'dalmatinerdb' LAST 60s`) aren't working anymore. With the same resource consumption by dalmatinerdb as in previous day.
Dalmatinerdb wrote the following errors to logs:
```
2016-12-07 05:25:43.087 [error] emulator Error in process <0.10661.2> on node 'dalmatinerdb@127.0.0.1' with exit value:
{{badmatch,{error,timeout}},[{dalmatiner_tcp,do_send,6,[{file,"/home/nginn/dalmatinerdb/_build/prod/lib/dalmatiner_db/src/dalmatiner_tcp.erl"},{line,107}]},{dalmatiner_tcp,loop,3,[{file,"/home/nginn/dalmatinerdb/_build/prod/lib/dalmatiner_db/src/dalmatiner_tcp.erl"},{line,66}]}]}
2016-12-07 05:25:43.087 [error] <0.10661.2> Ranch listener dalmatiner_tcp terminated with reason: no match of right hand value {error,timeout} in dalmatiner_tcp:do_send/6 line 107
```
Unlike the situation I had [here](https://github.com/dalmatinerdb/dalmatinerdb-datasource/issues/17), frontend doesn't have any errors and it doesn't look like I send too big queries because it fails even in queries asking for a stat in less than 60s timeframe.
**So my question is: what might be a reason(s) for such behavior?** I don't see that dalmatinerdb exhausts system resources and I even thought that it can handle more load in current setup. But if such problems start already, I'm not sure how to predict it's behavior.

**Comment by Licenser** [comment]
Without more information all I can do is take a blind guess.


A load of 20 is quite high so it seems the cpu is fairly saturated.

Another thing that you might experience is as all instances are started roughly around the time caches are filled up about equally and can cause spikes in load when they are flushed all at the same time reading at such times can generate timeouts.

**Comment by nginn** [comment]
yep, that's right, I just used atom processors and they got saturated extremely fast.
Thanks for your answer :) I think the issue might be closed as dalmatinerdb has nothing to do with my problem -- it's a hardware one.
